### ISSUE TITLE
HoloLensForCV.SensorFrameStreamer.Enable() - unauthorised access exception

### ISSUE THREAD

**Issue by A00107408** [microsoft/HoloLensForCV#148]
I am using HoloLensForCV via a Unity project: https://github.com/doughtmw/ArUcoDetectionHoloLens-Unity

I am making a Rubik's Cube solving AR application.

I would also like to track the user's eye movements via the HoloLens 2 eye tracking sensors to gauge their cognitive load.

So I am trying to use MRTK to track the user's eyes, and HoloLensForCV to track the Rubik's Cube. Is this possible?

I get the exception "_At least one of either InternetClientServer or PrivateNetworkClientServer capabilities is required to listen for or receive traffic_" when I try to access the raw video feed using HoloLensForCV in a project with MRTK.

Is it possible to use MRTK and HoloLensForCV in the same project for my needs? or does HoloLensForCV also include access to the eye tracking sensors so I don't have to use MRTK?

**Comment by emeraldy** [comment]
Hello,

Since you mentioned Hololens 2 eye tracking, maybe hololens2forcv is what you are looking for (https://github.com/microsoft/HoloLens2ForCV)? The latest MRTK supports both Hololens and Hololens 2. As for that exception, make sure you have those capabilities ticked, which can be done either in unity's player settings when you are about to build the unity project or in Package.appxmanifest within the corresponding visual studio project spat out by the aforementioned unity build process. I assume you are working with Hololens 2 so maybe posting your questions there will get better answers.

**Comment by A00107408** [comment]
Ok thank you
