### ISSUE TITLE
Trying to build but LNK1356: cannot find library `*.lib' specified to be whole archived

### ISSUE THREAD

**Issue by juansuerogit** [Microsoft/HoloLensForCV#16]
11>LINK : fatal error LNK1356: cannot find library `*.lib' specified to be whole archived
11>Done building project "Streamer.vcxproj" -- FAILED.

Im new at Unity, C++, as well as Hololens.  :)
I have Visual Studio 2017 15.5.2

my Visual Studio is configured for UWP if i recall.

**Comment by polszta** [comment]
Yes, there seems to have been a change in behavior for the linker in that regard. The fix is to remove the /WHOLEARCHIVE:* linker command line option from the failing projects. I'll see about cherry-picking the fix from a branch where the issue was already addressed.

**Comment by fogbridgegit** [comment]
thanks.  since i havent done C++ since CS 101 back in 1992 im gonna go ahead and just create a brand new C++ UWP app and copy over the files line by line.   Do you know what a good resource or book for C++ / UWP / Hololens?   Id love to stream the video onto the Jetson TX2 board cause it have all those deep learning tools.     Specifically feel i want to do that by first learning what HololensCV has and how that maps to whats coming with the Hololens AI chip and whats there for the Jetson Tx2.    If i write a C++ directx app that uses HololensforCV does that mean there is only 1 process running on the hololens so i cant run my CV code as a service on the hololens itself?  so many questions.

**Comment by polszta** [comment]
This was fixed a while ago - closing the issue.
