### ISSUE TITLE
Camera intrinsics "CameraProjectionTransform" for depth camera always null

### ISSUE THREAD

**Issue by felixvh** [Microsoft/HoloLensForCV#38]
Hi all,

I am trying to get the above mentioned CameraProjectionTransform as mentioned in https://docs.microsoft.com/en-us/windows/mixed-reality/locatable-camera#images-with-coordinate-systems 

Unfortunately the matrix is always null for the depth camera. For the rgb camera on the other hand it is not null. Anyone has an idea why and if there is another way to get the values?

**Comment by FracturedShader** [comment]
The depth cameras do not fully implement the specifications that were created largely for the Kinect (which is ridiculous), instead they store things under undocumented GUIDs in the properties object. You can see them doing this in the `FrameArrived` function of [MediaFrameReaderContext.cpp](https://github.com/Microsoft/HoloLensForCV/blob/master/Shared/HoloLensForCV/MediaFrameReaderContext.cpp). [Line 226](https://github.com/Microsoft/HoloLensForCV/blob/master/Shared/HoloLensForCV/MediaFrameReaderContext.cpp#L226) (at the time of writing) specifically handles the projection transform. Keep in mind that this is not the projection matrix from screen space to camera space, but something else entirely. To get from the flat camera image out into the world you actually need the unproject map, which is much more annoying of a process since you have to cast a property to a custom made "CameraIntrinsics" object that is not the same as the CameraIntrinsics in the Microsoft documentation. They do this around [line 268](https://github.com/Microsoft/HoloLensForCV/blob/master/Shared/HoloLensForCV/MediaFrameReaderContext.cpp#L268) (at time of writing) of the same file. They then use the [`MapImagePointToCameraUnitPlane`](https://github.com/Microsoft/HoloLensForCV/blob/master/Shared/HoloLensForCV/ICameraIntrinsics.h#L27) function to manually generate an unproject map.

**Comment by felixvh** [comment]
Thanks! 
Additionally, I got an answer from Windows. I'll post it, in case somebody has the same issue. They say:

" 
You are correct, not all media properties are available for the research mode streams.

Here’s an example how to get from image to world coordinates:

https://github.com/Microsoft/HoloLensForCV/blob/feature/ArUcoMarkers/Samples/ArUcoMarkerTracker/AppMain.cpp

Most of relevant code is in DetectArUcoMarkers and TrackArUcoMarkers functions.

Please note that this sample is still work in progress. There is also some similar code in the Recorder tool.
"

**Comment by doughtmw** [comment]
I'm not able to find the **OpenCV.HoloLens.341.0.0** Nuget package to run the feature/ArUcoMarkers branch. Has it been made publicly available?

**Comment by AlexSyx** [comment]
Still have no idea how to get the depth sensor's intrinsics.How did you get the parameters such as focal length of depth sensor ?Help PLS!!

**Comment by Huangying-Zhan** [comment]
#63
